### ISSUE TITLE
mppnccombine executable is not specified in config.yaml

### ISSUE THREAD

**Issue by aidanheerdegen** [COSIMA/1deg_jra55_ryf#2]
Collate will not work for a new user who does not already have an mppnccombine executable in their model bin directory.

Full path to mppnccombine should be specified in `config.yaml`

**Comment by aekiss** [comment]
This will be fixed in all the [standard control directories](https://github.com/COSIMA/access-om2/tree/master/control) once I merge in the `ak-dev` branch.
